services:
  - type: web
    runtime: docker
    name: php-apache-server
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    buildCommand: docker build --target php_apache --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") -t php-apache .

  - type: web
    runtime: docker
    name: mysql
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    buildCommand: docker build --target mysql --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") -t mysql .

  - type: web
    runtime: docker
    name: phpmyadmin
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    buildCommand: docker build --target phpmyadmin -t phpmyadmin .
    envVars:
      - key: PMA_HOST
        value: mysql
