services:
  - type: web
    runtime: docker
    name: enigma_one_server
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    buildCommand: docker build --target php_apache --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") -t php-enigma_one_server:latest .
    envVars:
      - fromGroup: ENIGMA_ONE
