services:
  - type: web
    runtime: docker
    name: php-apache-server
    plan: free
    dockerfilePath: /Dockerfiles/server/.
    dockerContext: .
    buildCommand: docker build --target php_apache --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") -t php-apache .
    envVars:
      - fromGroup: ENIGMA_ONE_PHP_ENV



  - type: web
    runtime: docker
    name: enigma_one_mysql
    plan: free
    dockerfilePath: Dockerfiles/mysql/.
    dockerContext: .
    buildCommand: docker build --target mysql --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") -t mysql .
    envVars:
      - fromGroup: ENIGMA_ONE_MYSQL_ENV

  - type: web
    runtime: docker
    name: phpmyadmin
    plan: free
    dockerfilePath: Dockerfiles/phpmyadmin/.
    dockerContext: .
    buildCommand: docker build --target phpmyadmin -t phpmyadmin .
    envVars:
      - fromGroup: ENIGMA_ONE_PHP_ADMIN_ENV
